import {SpellLab} from './engine.mjs';
const $=id=>document.getElementById(id),stage=$('stage'),ctx=stage.getContext('2d'),dc=$('detail').getContext('2d');
const files=new Map(),keys={},TAU=Math.PI*2;let data,lab,map,selected=0,paused=false,rate=1,last=0,inspectLoop=false,inspectTime=0,inspectFrame=0,seen=0,audioContext=null;
const load=src=>new Promise((resolve,reject)=>{const im=new Image;im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Image introuvable : '+src));im.src=src});
function choose(index){selected=index;inspectTime=0;inspectFrame=0;const a=data.actions[index];$('title').textContent=a.name;$('description').textContent=a.subtitle;$('duration').textContent=`${a.total_ms} ms`;$('impact').textContent=`${a.event_ms} ms`;$('phasebar').innerHTML=a.frames.map(f=>`<i style="flex:${f.duration_ms}"></i>`).join('');$('scrub').value=0;drawInspector()}
function cast(index){choose(index);lab.cast(data.actions[index].id);stage.focus({preventScroll:true});enableAudio()}
function enableAudio(){if(!$('audio').checked)return;try{audioContext??=new AudioContext();if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});}catch{$('soundhint').textContent='Son indisponible sur ce navigateur.'}}
function tone(freq,duration,gain=.04){if(!audioContext||!$('audio').checked)return;const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime;o.type='triangle';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(35,freq*.28),t+duration);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(audioContext.destination);o.start(t);o.stop(t+duration)}
function ellipse(c,x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,TAU);c.fill()}
function line(c,points,color,width=2){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(...points[0]);for(const p of points.slice(1))c.lineTo(...p);c.stroke()}
function sprite(c,file,x,y,scale=.55,alpha=1){c.save();c.globalAlpha=alpha;c.drawImage(files.get(file),x-data.pivot[0]*scale,y-data.pivot[1]*scale,768*scale,768*scale);c.restore()}
function backdrop(){const mode=$('ground').value;if(mode==='map'){const scale=Math.max(1280/map.width,630/map.height);ctx.drawImage(map,(1280-map.width*scale)/2,(630-map.height*scale)/2,map.width*scale,map.height*scale);ctx.fillStyle='#091b18a0';ctx.fillRect(0,0,1280,630)}else{ctx.fillStyle=mode==='light'?'#d2d5c4':'#263b34';ctx.fillRect(0,0,1280,630)}
 ctx.save();ctx.globalAlpha=mode==='map'?.16:.27;ctx.strokeStyle=mode==='light'?'#617762':'#a1bea0';ctx.lineWidth=1;for(let i=-15;i<28;i++){ctx.beginPath();ctx.moveTo(i*80,230);ctx.lineTo(i*80+800,630);ctx.stroke();ctx.beginPath();ctx.moveTo(i*80,230);ctx.lineTo(i*80-800,630);ctx.stroke()}ctx.restore();
 const g=ctx.createLinearGradient(0,0,0,130);g.addColorStop(0,'#071410c9');g.addColorStop(1,'#07141000');ctx.fillStyle=g;ctx.fillRect(0,0,1280,130);
}
function target(t){if(t.hp<=0)return;const x=t.x+(t.flash>0?Math.sin(t.flash*60)*5:0),y=t.y;ellipse(ctx,x,y+3,35,12,'#06190d75');
 ctx.fillStyle='#16291f';ctx.beginPath();ctx.moveTo(x-30,y);ctx.lineTo(x-20,y-152);ctx.lineTo(x,y-187);ctx.lineTo(x+29,y-148);ctx.lineTo(x+27,y-5);ctx.closePath();ctx.fill();
 ctx.fillStyle=t.flash>0?'#d3ddbd':'#687365';ctx.beginPath();ctx.moveTo(x-23,y-7);ctx.lineTo(x-15,y-148);ctx.lineTo(x,y-173);ctx.lineTo(x+11,y-145);ctx.lineTo(x+13,y-9);ctx.closePath();ctx.fill();ctx.fillStyle='#384c3a';ctx.beginPath();ctx.moveTo(x+11,y-145);ctx.lineTo(x+22,y-151);ctx.lineTo(x+22,y-11);ctx.lineTo(x+13,y-9);ctx.fill();
 ctx.strokeStyle=t.flash>0?'#fff4c6':'#c1b587';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x-1,y-120,17,25,0,0,TAU);ctx.stroke();line(ctx,[[x-1,y-149],[x-1,y-88]],'#c1b587');line(ctx,[[x-11,y-120],[x+10,y-120]],'#c1b587');
 ctx.fillStyle='#081811';ctx.fillRect(x-28,y-204,56,5);ctx.fillStyle='#c5c58c';ctx.fillRect(x-28,y-204,56*t.hp/100,5);ctx.fillStyle='#d1d6bc';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText(`CIBLE ${t.id+1}`,x,y+26);
}
function fx(e){const p=e.age/e.life,fade=Math.sin(Math.min(1,p)*Math.PI),x=e.x,y=e.y;ctx.save();ctx.globalAlpha=(1-p)*.9;ctx.strokeStyle=e.color;ctx.fillStyle=e.color;ctx.shadowColor=e.color;ctx.shadowBlur=14;
 if(e.kind==='melee'){const u=Math.min(1,e.age/.11);line(ctx,[[x+65,y-164],[x+90+150*u,y-164]],e.color,7*(1-p)+1);line(ctx,[[x+120,y-172],[x+245,y-164],[x+128,y-157]],'#f8f1c4',2);}
 if(e.kind==='sweep'){ctx.save();ctx.translate(x+32,y-98);ctx.scale(1,.64);ctx.lineWidth=22*(1-p)+1;ctx.beginPath();ctx.arc(0,0,195,-1.5,-1.5+4.4*Math.min(1,e.age/.22));ctx.stroke();ctx.lineWidth=3;ctx.strokeStyle='#edf6cb';ctx.beginPath();ctx.arc(0,0,212,-1.5,-1.5+4.4*Math.min(1,e.age/.22));ctx.stroke();ctx.restore()}
 if(e.kind==='guard'){ctx.save();ctx.translate(x+55,y-126);ctx.rotate(-.16);ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,0,68+fade*20,114+fade*10,0,0,TAU);ctx.stroke();ctx.globalAlpha*=.23;ctx.fill();ctx.restore();ellipse(ctx,x,y,100*fade+35,24*fade+9,'#ecd798')}
 if(e.kind==='dash'){for(let i=0;i<5;i++)line(ctx,[[x-105-i*10,y-90+i*23],[x+30-i*13,y-90+i*23]],e.color,3*(1-p))}
 if(e.kind==='bash'){ctx.lineWidth=8*(1-p)+1;ctx.beginPath();ctx.ellipse(x+155+60*p,y-127,25+55*p,72+15*p,-.18,-1.4,1.5);ctx.stroke();}
 if(e.kind==='shot'){ctx.lineWidth=3;ctx.beginPath();ctx.arc(x+90,y-187,18+55*p,0,TAU);ctx.stroke()}
 if(e.kind==='hit'||e.kind==='dissolve'){for(let i=0;i<9;i++){const a=i*2.399,r=10+p*(e.kind==='hit'?65:95),xx=x+Math.cos(a)*r,yy=y-45+Math.sin(a)*r*.75;ctx.save();ctx.translate(xx,yy);ctx.rotate(a+p);ctx.fillRect(-2,-5,4,10);ctx.restore()}if(e.kind==='hit'){ctx.shadowBlur=0;ctx.fillStyle='#fff2cb';ctx.font='bold 24px Georgia';ctx.textAlign='center';ctx.fillText(e.text,x,y-105-p*35)}}ctx.restore();
}
function draw(){if(!lab)return;ctx.clearRect(0,0,1280,630);ctx.save();if($('shake').checked&&lab.freeze>0){const k=Math.min(1,lab.freeze/.04)*3;ctx.translate(Math.sin(lab.time*165)*k,Math.cos(lab.time*135)*k*.5)}backdrop();
 const p=lab.player;ellipse(ctx,p.x,p.y+5,48,15,'#03110966');if(lab.move){ctx.strokeStyle='#d4dbad';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(lab.move.x,lab.move.y,12,5,0,0,TAU);ctx.stroke()}
 const active=lab.active;let file=active?active.spell.frames[lab.phase].file:lab.walking?data.walk[Math.floor(p.walk*10)%12].file:data.idle;
 const actors=[...lab.targets.map(t=>({y:t.y,draw:()=>target(t)})),{y:p.y,draw:()=>{if($('vfx').checked&&active?.spell.mode==='dash'&&lab.phase===1){sprite(ctx,file,p.x-40,p.y,.55,.17);sprite(ctx,file,p.x-75,p.y,.55,.08)}sprite(ctx,file,p.x,p.y);}}].sort((a,b)=>a.y-b.y);for(const a of actors)a.draw();
 if($('vfx').checked){for(const e of lab.effects)fx(e);if(p.shield>0){ctx.save();ctx.globalAlpha=.24*Math.min(1,p.shield);ctx.strokeStyle='#f1ce8c';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y,70,22,0,0,TAU);ctx.stroke();ctx.restore()}for(const b of lab.projectiles){ctx.save();ctx.shadowColor='#a0eee2';ctx.shadowBlur=14;line(ctx,[[b.x-95,b.y],[b.x,b.y]],'#9ee1ca',4);ctx.fillStyle='#e6ffe5';ctx.beginPath();ctx.moveTo(b.x+21,b.y);ctx.lineTo(b.x-8,b.y-7);ctx.lineTo(b.x-1,b.y);ctx.lineTo(b.x-8,b.y+7);ctx.fill();ctx.restore()}}
 ctx.restore();$('status').textContent=lab.message;$('score').textContent=`${lab.casts} gestes · ${lab.hits} impacts`;
 for(const [i,b] of [...$('spells').children].entries()){const s=data.actions[i],cd=lab.cooldowns[s.id]||0;b.classList.toggle('active',active?.spell.id===s.id);b.querySelector('.cd').style.width=`${Math.max(0,1-cd/(s.cooldown_ms/1000))*100}%`;b.setAttribute('aria-pressed',String(active?.spell.id===s.id))}
 drawInspector();
}
function drawInspector(){if(!lab)return;const a=data.actions[selected];if(inspectLoop){let t=(inspectTime%(a.total_ms/1000+.3));inspectFrame=3;for(let i=0;i<4;i++){t-=a.frames[i].duration_ms/1000;if(t<0){inspectFrame=i;break}}}else if(lab.active?.spell.id===a.id)inspectFrame=lab.phase;
 dc.clearRect(0,0,500,500);ellipse(dc,235,440,70,17,'#061c1566');dc.strokeStyle='#899a7340';dc.lineWidth=1;for(let i=0;i<8;i++){dc.beginPath();dc.moveTo(0,430+i*9);dc.lineTo(500,430+i*9);dc.stroke()}sprite(dc,a.frames[inspectFrame].file,235,435,.66);$('scrub').value=inspectFrame;$('phase').textContent=`${inspectFrame+1} / 4 · ${a.frames[inspectFrame].phase}`;[...$('phasebar').children].forEach((e,i)=>e.classList.toggle('current',i===inspectFrame))}
function tick(now){if(!last)last=now;const dt=Math.min(.05,(now-last)/1000)*rate;last=now;if(lab&&!paused){lab.step(dt,keys);inspectTime+=dt;for(const e of lab.events.slice(seen)){if(e.type==='release')tone(e.id==='guard'?260:155,.12,.025);if(e.type==='hit')tone(75,.15,.06)}seen=lab.events.length}draw();requestAnimationFrame(tick)}
$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Reprendre':'Pause'};
$('reset').onclick=()=>{lab.reset();seen=0;for(const k in keys)delete keys[k];draw()};$('speed').onchange=()=>rate=Number($('speed').value);$('audio').onchange=enableAudio;
$('inspectPlay').onclick=()=>{inspectLoop=!inspectLoop;$('inspectPlay').textContent=inspectLoop?'Arrêter la boucle':'Boucler ce geste';inspectTime=0};
$('scrub').oninput=()=>{inspectLoop=false;inspectFrame=Number($('scrub').value);$('inspectPlay').textContent='Boucler ce geste';if(lab.active)lab.active=null;drawInspector()};
const mapping={ArrowLeft:'left',KeyA:'left',KeyQ:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyW:'up',KeyZ:'up',ArrowDown:'down',KeyS:'down'};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target.tagName)||!lab)return;if(e.code.startsWith('Digit')&&Number(e.code.slice(5))>=1&&Number(e.code.slice(5))<=6){e.preventDefault();if(!e.repeat)cast(Number(e.code.slice(5))-1)}if(mapping[e.code]){e.preventDefault();keys[mapping[e.code]]=true;lab.move=null}if(e.code==='KeyR'&&!e.repeat)$('reset').click()});window.addEventListener('keyup',e=>{if(mapping[e.code])delete keys[mapping[e.code]]});window.addEventListener('blur',()=>{for(const k in keys)delete keys[k]});
stage.onpointerdown=e=>{stage.focus({preventScroll:true});enableAudio();if(lab.active)return;const r=stage.getBoundingClientRect();lab.move={x:Math.max(180,Math.min(1080,(e.clientX-r.left)*1280/r.width)),y:Math.max(330,Math.min(555,(e.clientY-r.top)*630/r.height))}};
(async()=>{const response=await fetch('manifest.json');if(!response.ok)throw Error('Manifeste introuvable');data=await response.json();const paths=[data.idle,...data.walk.map(f=>f.file),...data.actions.flatMap(a=>a.frames.map(f=>f.file))];await Promise.all([...new Set(paths)].map(async f=>files.set(f,await load(f))));map=await load('map.png');lab=new SpellLab(data);
 $('spells').innerHTML=data.actions.map((a,i)=>`<button class="spell" style="--accent:${a.color}" aria-label="${i+1} ${a.name}"><span class="n">${i+1}</span><strong>${a.name}</strong><small>${a.subtitle}</small><span class="cd"></span></button>`).join('');[...$('spells').children].forEach((b,i)=>b.onclick=()=>cast(i));choose(0);$('load').remove();
 window.spellLab={ready:true,lab,getState:()=>lab.snapshot(),select:choose,cast,index:index=>cast(index),pause:v=>{paused=v;$('pause').textContent=paused?'Reprendre':'Pause'},step:dt=>{lab.step(dt);draw()},setInspector:i=>{inspectLoop=false;lab.active=null;inspectFrame=i;drawInspector()},render:draw,loadedImages:files.size};requestAnimationFrame(tick);
})().catch(e=>{$('error').textContent=e.message;$('load').textContent='Chargement incomplet — '+e.message});
