extends RefCounted
## Per-card art direction: silhouette, construction variant, tail seconds, span in cells, intent.
## These are presentation values, never changes to damage, range or activation duration.
const MOTIFS := [
	"cut",
	"lance",
	"brand",
	"wound",
	"aegis",
	"stride",
	"shackle",
	"repulse",
	"tether",
	"wither",
	"crystal",
	"plume",
	"thunder",
	"shade",
	"discord",
	"dream",
	"crown",
]
const CARDS := {
	"a_open": ["brand", 0, .70, 1.65, "Deux crochets ouvrent un point faible au-dessus du buste."],
	"a_finish": [
		"lance",
		1,
		.48,
		1.85,
		"Une pointe entre entre deux éclats latéraux, puis s'éteint.",
	],
	"a_cut": ["cut", 1, .58, 1.85, "Une incision oblique laisse un sillage rouge qui descend."],
	"a_step": [
		"stride",
		0,
		.48,
		1.65,
		"Une plume latérale quitte les pieds et se reforme à l'arrivée.",
	],
	"a_parry": ["aegis", 0, .58, 1.65, "Deux pans courts interceptent devant le buste."],
	"a_dagger": ["dagger", 0, .32, 1.65, "Une lame fine suit la direction du contact confirmé."],
	"a_ambush": [
		"cut",
		2,
		.56,
		1.95,
		"Un croissant décentré rejoint brusquement la cible par le flanc.",
	],
	"a_sweep": [
		"cut",
		3,
		.72,
		2.15,
		"Deux grandes coupes se croisent sur chaque ennemi réellement touché.",
	],
	"a_hamstring": [
		"shackle",
		0,
		.68,
		1.70,
		"Une coupe basse se resserre en liens autour des chevilles.",
	],
	"a_push": [
		"repulse",
		0,
		.50,
		1.75,
		"Un éventail compact chasse l'air depuis le point de contact.",
	],
	"a_execute": [
		"cut",
		4,
		.76,
		2.20,
		"Une longue faux lumineuse s'abat ; aucun faux signal de bonus.",
	],
	"a_pull": [
		"tether",
		0,
		.72,
		1.85,
		"Un crochet recourbé et ses filaments reviennent vers le lanceur.",
	],
	"a_blind": [
		"wither",
		0,
		.86,
		1.85,
		"Un voile de poussière se déchire autour des épaules affaiblies.",
	],
	"a_pierce": [
		"lance",
		0,
		.44,
		1.80,
		"Une pointe resserrée traverse le buste et se disperse en aiguilles.",
	],
	"a_escape": ["stride", 1, .70, 1.90, "Trois rubans fuyants s'effilent derrière les pieds."],
	"g_guard": [
		"aegis",
		1,
		.85,
		1.90,
		"Trois pans d'airain translucide se dressent autour du buste.",
	],
	"g_push": [
		"repulse",
		1,
		.65,
		2.00,
		"Une poussée large projette des lamelles d'airain vers l'extérieur.",
	],
	"g_hit": ["lance", 2, .60, 1.95, "Un coin d'airain épais percute, avec deux éclats de bord."],
	"g_step": ["stride", 2, .60, 1.60, "Un pli bas et lourd avance jusqu'à la nouvelle position."],
	"g_slow": [
		"shackle",
		1,
		.78,
		1.80,
		"Deux bandes basses freinent l'élan sans enfermer le corps entier.",
	],
	"g_pull": ["tether", 1, .82, 2.00, "Deux liens tendus convergent vers la ligne du gardien."],
	"g_wall": [
		"aegis",
		2,
		1.00,
		2.05,
		"Des voiles verticaux ferment les flancs comme un passage défendu.",
	],
	"g_sweep": ["cut", 5, .78, 2.20, "Un balayage horizontal ample fend les silhouettes touchées."],
	"g_crush": ["repulse", 2, .85, 2.25, "Un noyau dense éclate en trois nervures divergentes."],
	"g_mark": ["brand", 1, .80, 1.80, "Une fourche d'airain encadre la menace au-dessus du buste."],
	"g_riposte": ["cut", 6, .70, 2.00, "Un revers remontant renvoie un éclat lourd depuis le bas."],
	"g_shot": [
		"lance",
		3,
		.58,
		2.00,
		"Un javelot large laisse une hampe de lumière brisée au contact.",
	],
	"g_weaken": ["wither", 1, .85, 1.95, "Des éclats d'arme s'écartent puis retombent des épaules."],
	"g_charge": [
		"stride",
		3,
		.72,
		2.00,
		"Un sillage en pointe accompagne départ et arrivée de la percée.",
	],
	"g_punish": [
		"lance",
		4,
		.62,
		1.95,
		"Deux pointes décalées frappent le déséquilibre de la cible.",
	],
	"r_shot": ["lance", 5, .50, 1.90, "Une flèche longue se termine par des éclats d'empennage."],
	"r_step": ["stride", 4, .50, 1.70, "Deux plumes rasent le sol sur le côté."],
	"r_slow": [
		"shackle",
		2,
		.72,
		1.80,
		"Des liens fins jaillissent de l'impact jusqu'aux chevilles.",
	],
	"r_push": [
		"repulse",
		3,
		.62,
		1.95,
		"Un trait ouvre un cône étroit orienté à l'opposé du tireur.",
	],
	"r_guard": [
		"aegis",
		3,
		.68,
		1.70,
		"Deux voiles inclinés couvrent les flancs sans faire une armure lourde.",
	],
	"r_mark": ["brand", 2, .82, 1.80, "Trois pointes de visée se referment sur un foyer suspendu."],
	"r_hunt": [
		"lance",
		6,
		.62,
		2.00,
		"Un trait barbelé rejoint le centre, suivi de deux petites pointes.",
	],
	"r_fan": [
		"lance",
		7,
		.78,
		2.20,
		"Trois traits en éventail convergent sur chaque impact de la croix.",
	],
	"r_close": [
		"repulse",
		4,
		.50,
		1.70,
		"Une onde courte et basse repousse depuis le coup de crosse.",
	],
	"r_bleed": ["wound", 0, .82, 1.90, "Des barbes rouges arrachent trois filaments descendants."],
	"r_long": ["lance", 8, .76, 2.25, "Une longue aiguille lumineuse laisse deux sillages étagés."],
	"r_move": [
		"lance",
		9,
		.56,
		1.90,
		"Un trait oblique et une plume latérale évoquent le tir mobile.",
	],
	"r_escape": ["stride", 5, .76, 2.00, "Des plumes traversent la ligne et s'ouvrent à l'arrivée."],
	"r_pull": [
		"tether",
		2,
		.82,
		2.00,
		"Une ligne centrale et ses barbes se rétractent vers l'archer.",
	],
	"r_weak": [
		"wither",
		2,
		.76,
		1.80,
		"Deux éclats cèdent à hauteur des mains, puis se dispersent.",
	],
	"t_frost": [
		"crystal",
		0,
		.82,
		1.95,
		"Une pointe de givre ouvre un bouquet cristallin au contact.",
	],
	"t_fire": ["plume", 0, 1.05, 2.00, "Une braise éclate en trois langues de feu éthéré."],
	"t_mark": ["brand", 3, .90, 1.90, "Un sceau en crochets d'ombre suspend un foyer violet."],
	"t_guard": [
		"aegis",
		4,
		1.00,
		2.00,
		"Des voiles de cendre remontent en protection autour du buste.",
	],
	"t_step": ["stride", 6, .72, 1.80, "La brume se plie au départ et se déplie à l'arrivée."],
	"t_bolt": [
		"thunder",
		0,
		.62,
		2.05,
		"Un arc cassé ramifie au contact avant une extinction rapide.",
	],
	"t_hex": ["shade", 0, .85, 1.95, "Deux morsures d'ombre convergent dans le buste."],
	"t_weak": ["wither", 3, .98, 1.95, "La lumière des épaules se défait en cendres descendantes."],
	"t_pull": ["tether", 3, .95, 2.10, "Trois volutes profondes se resserrent vers le lanceur."],
	"t_push": ["repulse", 5, .80, 2.10, "Des lames de souffle minéral divergent depuis le contact."],
	"t_burn": ["ember", 0, .68, 1.70, "Une ignition courte accroche des braises aux flancs."],
	"t_ice": [
		"crystal",
		1,
		1.00,
		2.20,
		"Un éventail de cristaux éclate sur chaque cible de la croix.",
	],
	"t_storm": [
		"thunder",
		1,
		.95,
		2.35,
		"Trois branches de foudre frappent ensemble puis laissent une rémanence.",
	],
	"t_touch": ["shade", 1, .72, 1.85, "Une griffe d'ombre remonte depuis le point de contact."],
	"t_escape": [
		"stride",
		7,
		.90,
		2.00,
		"Deux grandes nappes de brume se dissocient puis se réunissent.",
	],
	"a_venom": [
		"wound",
		1,
		1.00,
		2.00,
		"Des filaments carmin se ramifient ; le Styx inflige ici un saignement.",
	],
	"a_disarm": [
		"discord",
		0,
		.85,
		1.90,
		"Une coupure rompt deux arcs près des mains ; perte de PA, pas de PM.",
	],
	"a_lure": ["tether", 4, 1.00, 2.00, "Un fil d'ombre sinueux appelle la cible vers le lanceur."],
	"a_stasis": [
		"dream",
		0,
		1.10,
		2.00,
		"Deux voiles en suspension referment un sommeil sur la cible marquée.",
	],
	"a_reap": [
		"cut",
		7,
		1.00,
		2.45,
		"Deux faux opposées et un large sillage carmin composent la moisson.",
	],
	"a_phantom": [
		"stride",
		8,
		1.00,
		2.10,
		"Une silhouette de brume se déchire puis renaît au point d'arrivée.",
	],
	"g_bastion": [
		"aegis",
		5,
		1.20,
		2.30,
		"Quatre hauts pans d'airain se dressent et laissent le centre lisible.",
	],
	"g_prison": [
		"shackle",
		3,
		.95,
		2.00,
		"Des arceaux de bronze resserrent la partie basse du corps.",
	],
	"g_fault": [
		"plume",
		1,
		.90,
		1.85,
		"Des veines incandescentes ouvrent les dalles réellement embrasées.",
	],
	"g_crash": ["repulse", 6, 1.00, 2.40, "Un front de rempart éclate en larges nervures d'airain."],
	"g_hook": [
		"tether",
		5,
		1.05,
		2.25,
		"Trois chaînes spectrales crantées se rétractent vers le gardien.",
	],
	"g_silence": [
		"discord",
		1,
		.95,
		2.05,
		"Un choc fend les arcs d'incantation en fragments suspendus.",
	],
	"r_caltrop": [
		"crystal",
		2,
		.85,
		1.80,
		"Des dents de givre basses occupent chaque dalle du piège.",
	],
	"r_embers": [
		"plume",
		2,
		.90,
		1.90,
		"L'impact du trait éparpille des îlots de braises sur les dalles.",
	],
	"r_net": [
		"shackle",
		4,
		1.00,
		2.05,
		"Un filet de lumière se rabat autour des jambes puis se tend.",
	],
	"r_scatter": [
		"lance",
		10,
		1.00,
		2.40,
		"Cinq pointes crépusculaires convergent sur chaque ennemi touché.",
	],
	"r_horizon": [
		"stride",
		9,
		.95,
		2.15,
		"Des rubans très étirés s'évanouissent entre départ et arrivée.",
	],
	"r_bounty": [
		"lance",
		11,
		.90,
		2.30,
		"Un trait de chasse à trois barbes concentre un contact puissant.",
	],
	"t_flamewall": [
		"ember",
		1,
		.50,
		1.75,
		"Des foyers bas persistent sur la croix exacte de braises.",
	],
	"t_glacier": [
		"frost",
		0,
		.58,
		1.65,
		"Des veines asymétriques poussent à l'intérieur des dalles gelées.",
	],
	"t_charm": [
		"tether",
		6,
		1.10,
		2.15,
		"Trois rubans chantants convergent ; aucune conversion d'équipe.",
	],
	"t_hourglass": [
		"dream",
		1,
		1.20,
		2.20,
		"Deux éventails opposés retiennent des grains de lumière en suspension.",
	],
	"t_disrupt": ["discord", 2, 1.00, 2.10, "Trois ondes décalées se brisent au-dessus du buste."],
	"t_cataclysm": [
		"crown",
		0,
		1.30,
		2.40,
		"Une couronne ouverte de flammes monte en cinq pointes autour des impacts.",
	],
	"i_a_open": ["brand", 4, .62, 1.60, "Deux petits crochets révèlent une faille furtive."],
	"i_a_strike": [
		"lance",
		12,
		.46,
		1.70,
		"Une lame courte rejoint la faille en laissant une écharde.",
	],
	"i_a_step": ["stride", 10, .48, 1.60, "Une plume basse dessine une approche oblique."],
	"i_a_cut": ["cut", 8, .56, 1.70, "Une coupe courte dépose une ligne rouge descendante."],
	"i_a_ambush": ["cut", 9, .58, 1.80, "Un revers furtif surgit du flanc de la silhouette."],
	"i_a_dagger": [
		"dagger",
		1,
		.38,
		1.55,
		"Une petite lame de diversion laisse deux éclats au contact.",
	],
	"i_a_escape": ["stride", 11, .70, 1.80, "Deux voiles se replient vers le sol avant l'arrivée."],
	"i_g_guard": ["aegis", 6, .82, 1.85, "Deux pans épais composent le premier rempart."],
	"i_g_hit": ["lance", 13, .58, 1.85, "Un coin lumineux court heurte depuis la garde."],
	"i_g_push": ["repulse", 7, .62, 1.85, "Deux nervures écartent la menace à hauteur du buste."],
	"i_g_pull": ["tether", 7, .78, 1.85, "Un lien en crochet ramène vers le rempart."],
	"i_g_weaken": ["wither", 4, .80, 1.80, "Des éclats courts se détachent des épaules désarmées."],
	"i_g_step": ["stride", 12, .60, 1.65, "Un voile bas se plante à la nouvelle position."],
	"i_g_punish": [
		"lance",
		14,
		.62,
		1.85,
		"Une pointe oblique se double d'un éclat de déséquilibre.",
	],
	"i_r_shot": ["lance", 15, .48, 1.75, "Une flèche claire laisse un empennage court."],
	"i_r_slow": [
		"shackle",
		5,
		.72,
		1.75,
		"Deux fils se nouent aux chevilles de la cible poursuivie.",
	],
	"i_r_push": ["repulse", 8, .60, 1.80, "Une flèche ouvre deux nervures de recul."],
	"i_r_step": ["stride", 13, .50, 1.60, "Une plume discrète accompagne le pas d'éclaireur."],
	"i_r_move": ["lance", 16, .54, 1.80, "Un trait incliné laisse une plume de côté."],
	"i_r_mark": ["brand", 5, .72, 1.65, "Deux pointes fines repèrent la proie au-dessus du buste."],
	"i_r_hunt": ["lance", 17, .60, 1.85, "Une flèche à deux barbes ferme la piste."],
	"i_t_frost": ["crystal", 3, .80, 1.80, "Trois petites dents de givre mordent depuis le bas."],
	"i_t_hex": ["shade", 2, .82, 1.85, "Un sceau latent se resserre en deux morsures d'ombre."],
	"i_t_mark": ["brand", 6, .80, 1.75, "Deux crochets de brume tracent le sceau naissant."],
	"i_t_fire": ["plume", 3, 1.00, 1.85, "Une gerbe de cendres ouvre trois langues souples."],
	"i_t_burn": ["ember", 2, .76, 1.65, "Des braises couvantes remontent brièvement aux flancs."],
	"i_t_pull": ["tether", 8, .90, 1.95, "Deux rubans d'ombre se rassemblent vers le lanceur."],
	"i_t_guard": ["aegis", 7, .90, 1.85, "Un voile de suie se divise en deux pans protecteurs."],
}
