import type { Snapshot } from '../types';

export const snapshotFixture: Snapshot = {
  meta: {
    schema_version: '2.1.0', generator_version: '2.1.0', generated_at_utc: '2026-08-05T12:00:00', source_game_commit: 'abc123456789abc123456789abc123456789abcd', source_branch: 'feature/test', source_worktree_dirty_before_export: false, source_git_available: true, source_generated_from_clean_checkout: true, godot_version: '4.7.1', project_name: 'Dungeon Draft v2', contract_version: '1.1.0', manifest_version: '2.1.0',
  },
  scope: {
    included_domains: ['characters', 'spells', 'items'],
    deferred_domains: [{ domain: 'rooms', reason: 'Détail reporté.', status: 'deferred' }],
    excluded_domains: [{ domain: 'debug', reason: 'Hors production.', path: 'res://debug' }],
  },
  summary: {
    characters: 1, disciplines: 1, spells: 1, items: 2, generic_rewards: 1, reward_pools: 2, runs: 1, rooms: 1, waves: 1, authored_wave_profiles: 1, selected_default_seed_wave_profiles: 1, minimum_played_wave_profiles: 1, maximum_played_wave_profiles: 1, encounters: 1, enemies: 1, enemy_spells: 1, ai_profiles: 1, runtime_facts: 1, eligible_first_run_equipment: 1, contract_conform: 1, contract_difference: 0, contract_unknown: 0, contract_not_evaluated: 1, audit_info: 1, audit_warning: 0, audit_blocking: 0,
  },
  contract: { version: '1.1.0', decisions: [{ key: 'combat.base_ap', value: 6, status: 'validated', truth_status: 'design_decision', source: 'Mission', rationale: 'Référence.' }] },
  runtime_facts: [{ key: 'progression.xp_per_effective_cast', value: 1, truth_status: 'observed', source_paths: ['res://characters/progression/character_progression_service.gd'], evidence: 'Valeur runtime.', notes: 'Baseline uniquement.' }],
  characters: [{
    id: 'elf', name: 'Élfe', description: 'Héroïne de test.', role: 'Polyvalente', presentation_summary: 'Quatre voies.', progression_summary: 'Une discipline', presentation_badge: 'Héroïne', team: 0, max_hp: 100, max_ap: 6, max_mp: 3, initiative: 10, attack_power: 20, force: 0, armour: 5, magic_resistance: 7, dodge: 0.1, resistances: { fire: 0.2 }, critical_chance: 0.05, critical_multiplier: 1.5, basic_attack_enabled: true, active_spell_slots: 4, spell_ids: ['elf_fireball'], discipline_ids: ['mage'], source_path: 'res://data/elf.tres', visual_scene_path: 'res://characters/elf.tscn', preview_visual_scene_path: '',
  }],
  spells: [{
    id: 'elf_fireball', discipline_id: 'mage', name: 'Boule de feu', description: 'Inflige des dégâts de feu.', referenced_by_character_ids: ['elf'], ap_cost: 3, minimum_range: 1, range: 5, needs_line_of_sight: true, cooldown_activations: 0, initial_cooldown: 0, max_uses_per_combat: 0, once_per_activation: false, can_target_enemy: true, can_target_ally: false, can_target_free_cell: true, can_target_self: false, aoe_shape: { value: 1, name: 'cross' }, aoe_size: 2, line_from_caster: false, damage: 20, heal: 0, shield_grant: 0, damage_type: { value: 1, name: 'magical' }, element: { value: 1, name: 'fire' }, critical_chance: 0.05, terrain_effect: { resource_type: 'TerrainEffectData', resource_path: 'res://terrain/fire.tres' }, applied_status: null, push_distance: 0, pull_distance: 0, collision_damage: 0, cluster_bonus_damage: 0, ap_drain: 0, teleport_behind_target: false, delayed_resolution: { value: 0, name: 'none' }, summon: null, summon_type: '', modifiers: [], serialization_warnings: [], icon_path: '', vfx_scene_path: '', sound_path: '', source_path: 'res://spells/fireball.tres',
  }],
  disciplines: [{
    id: 'mage', character_id: 'elf', name: 'Magie', description: 'Maîtrise élémentaire.', rank_count: 2, total_choice_count: 1, ranks: [{ rank: 1, required_total_xp: 0, choices: [], source_path: 'res://disciplines/mage1.tres' }, { rank: 2, required_total_xp: 5, choices: [{ upgrade_id: 'mage_power', name: 'Puissance', description: 'Ajoute des dégâts.', discipline_id: 'mage', rank: 2, target_spell_id: 'elf_fireball', prerequisite_ids: [], excluded_ids: [], modifiers: [{ resource_type: 'SpellModDamage', resource_path: 'res://mods/power.tres', damage_bonus: 5 }], source_path: 'res://upgrades/power.tres' }], source_path: 'res://disciplines/mage2.tres' }], source_path: 'res://disciplines/mage.tres',
  }],
  items: [
    { id: 'anneau', name: 'Anneau élémentaire', description: 'Renforce les sorts.', rarity: 'rare', tags: ['accessory', 'first_run_equipment_reward'], category: { value: 2, name: 'accessory' }, equipment_slot: { value: 1, name: 'ring' }, stack_limit: 1, compatible_character_ids: [], stat_modifiers: [{ stat_id: 'armure', value: -2, modifier_type: { value: 0, name: 'flat' }, source_path: 'res://items/ring.tres::armour' }], spell_modifiers: [], use_effect: { value: 0, name: 'none' }, use_value: 0, equippable: true, consumable: false, valid: true, pool_ids: ['first_run_equipment'], reward_fx_profile: '', reward_audio_profile: '', icon_path: '', inventory_icon_path: '', card_texture_path: '', source_path: 'res://items/ring.tres' },
    { id: 'potion', name: 'Potion de soin', description: 'Rend des points de vie.', rarity: 'common', tags: ['consumable'], category: { value: 1, name: 'consumable' }, equipment_slot: { value: 0, name: 'none' }, stack_limit: 3, compatible_character_ids: ['elf'], stat_modifiers: [], spell_modifiers: [], use_effect: { value: 1, name: 'heal' }, use_value: 20, equippable: false, consumable: true, valid: true, pool_ids: [], reward_fx_profile: '', reward_audio_profile: '', icon_path: '', inventory_icon_path: '', card_texture_path: '', source_path: 'res://items/potion.tres' },
  ],
  reward_pools: [
    { id: 'generic', name: 'Génériques', kind: 'generic_declared', mechanism: 'static', status: 'declared_and_referenced', required_tag: '', minimum_options: 0, item_ids: [], rewards: [{ id: 'heal', name: 'Soin', description: 'Soigne le groupe.', reward_type: { value: 0, name: 'team_heal' }, target_policy: { value: 0, name: 'team' }, value: 0.2, valid: true, usage_status: 'declared_and_referenced_by_service', source_path: 'res://rewards/heal.tres' }], source_path: 'res://services/rewards.gd' },
    { id: 'first_run_equipment', name: 'Équipements', kind: 'equipment_first_run', mechanism: 'seeded_deck_without_replacement', status: 'eligible_catalog', required_tag: 'first_run_equipment_reward', minimum_options: 1, item_ids: ['anneau'], rewards: [], source_path: 'res://services/equipment.gd' },
  ],
  runs: [{
    id: 'first_run', id_source: 'manifest_alias', identity_stability: 'derived', name: 'Première run', source_path: 'res://data/runs/first_run.tres', default_seed: 1337, target_duration_minutes: 30, extended_duration_minutes: 45, maximum_waves_per_room: 10, room_ids: ['first_run.room.01'], authored_room_count: 1, authored_wave_profile_count: 1, selected_default_seed_wave_profile_count: 1, minimum_played_wave_profile_count: 1, maximum_played_wave_profile_count: 1, selected_health_multiplier_max: 1, selected_attack_multiplier_max: 1, selected_reward_multiplier_max: 1, validation_status: 'valid', validation_errors: [],
  }],
  rooms: [{
    id: 'first_run.room.01', id_source: 'ordered_parent_index', identity_stability: 'derived', run_id: 'first_run', index: 1, name: 'Salle 1 - Pont ancien', source_path: 'res://data/rooms/room_01.tres', background_image_path: '', particles_scene_path: '', battle_scene_path: 'res://battle/battle.tscn', arena_generation_profile_path: '', arena_visual_profile_path: '', grid_layout_path: 'res://data/maps/room_01.tres', painted_map_visual_data_path: '', map_kind: 'painted', grid_width: 12, grid_height: 10, grid_dimensions_status: 'static_resource', available_wave_count: 1, minimum_wave_count: 1, maximum_wave_count: 1, resolved_default_seed_wave_count: 1, wave_resolution_status: 'exact_production_resolver', wave_resolution_method: 'RunWaveCountResolver.resolve_counts', wave_resolution_seed: 1337, wave_ids: ['first_run.room.01.wave.01'], default_encounter_id: 'encounter.room.01', hero_spawn_cells: [{ x: 1, y: 8 }], enemy_spawn_cells: [{ x: 8, y: 1 }], hero_spawn_cell_count: 1, enemy_spawn_cell_count: 1, ultimate_reward_base_chance_percent: 10, ultimate_reward_min_gain_per_wave: 2, ultimate_reward_max_gain_per_wave: 5, legacy_enemy_ids: ['goblin'], validation_status: 'valid', validation_errors: [],
  }],
  waves: [{
    id: 'first_run.room.01.wave.01', id_source: 'ordered_parent_index', identity_stability: 'derived', room_id: 'first_run.room.01', index: 1, name: 'Vague 1', source_path: 'res://data/waves/room_01_wave_01.tres', source_kind: 'resource', encounter_id: 'encounter.room.01', enemy_health_multiplier: 1, enemy_attack_multiplier: 1, reward_multiplier: 1, is_mandatory_profile: true, is_optional_profile: false, is_selected_by_default_seed: true, health_multiplier_runtime_target: 'Unit.max_hp', attack_multiplier_runtime_target: 'Unit.attack_power', attack_multiplier_effect_status: 'effective', attack_multiplier_effect_evidence: 'Fixture test.', scaled_initial_totals: { total_max_hp: 80, total_attack_power: 16 }, calculation_status: 'static_base_only', calculation_evidence: 'Fixture test.', validation_status: 'valid', validation_errors: [],
  }],
  encounters: [{
    id: 'encounter.room.01', id_source: 'resource_path', identity_stability: 'stable', source_path: 'res://data/encounters/room_01.tres', room_ids: ['first_run.room.01'], wave_ids: ['first_run.room.01.wave.01'], declared_room_index: 1, roster: [{ enemy_id: 'goblin', count: 1 }], roster_unit_entry_count: 1, roster_count_entry_count: 1, initial_enemy_count: 1, expanded_initial_enemy_ids: ['goblin'], allowed_spawn_groups: ['enemy'], formation_profiles: ['line'], living_enemy_cap: 2, shared_normal_summon_budget: 1, shared_chief_summon_budget: 0, disabled_ability_ids: [], maximum_formation_attempts: 5, minimum_path_distance_by_role: { skirmisher: 3 }, maximum_path_distance_by_role: { skirmisher: 7 }, summon_free_neighbor_requirement: 1, forbidden_initial_spawn_cells: [], forbidden_initial_spawn_cell_count: 0, base_totals: { initial_enemy_count: 1, total_max_hp: 80, total_max_ap: 4, total_max_mp: 4, total_attack_power: 16, average_initiative: 12, maximum_initiative: 12 }, role_counts: { skirmisher: 1 }, faction_counts: { goblin: 1 }, initial_enemy_spell_count: 1, summon_spell_count: 0, calculation_status: 'static_base_only', calculation_evidence: 'Fixture test.', validation_status: 'valid', validation_errors: [],
  }],
  enemies: [{
    id: 'goblin', id_source: 'explicit', identity_stability: 'stable', name: 'Gobelin éclaireur', description: 'Combattant mobile de mêlée.', source_path: 'res://data/units/enemies/goblin.tres', reachability: { initial_encounter_ids: ['encounter.room.01'], initial_room_ids: ['first_run.room.01'], summonable_by_spell_ids: [], initial_roster: true, summon_only: false }, team: 1, max_hp: 80, initiative: 12, max_ap: 4, max_mp: 4, attack_power: 16, force: 0, armour: 10, magic_resistance: 5, dodge: 2, resistances: { fire: 10 }, critical_chance: 0, critical_multiplier: 1.5, basic_attack_enabled: false, active_spell_slots: 1, spell_ids: ['goblin_strike'], ai_behavior: { value: 0, name: 'melee' }, combat_style: { value: 0, name: 'melee' }, preferred_range: 1, minimum_range: 1, maximum_range: 1, keep_distance: false, ai_profile_id: 'goblin_rush', faction_id: 'goblin', tactical_role_id: 'skirmisher', linked_commander_role_id: '', proximity_armor_source: '', proximity_armor_per_living_neighbor: 0, proximity_armor_max_neighbors: 0, first_forced_movement_reduction_per_activation: 0, visual_scene_path: '', preview_visual_scene_path: '', effect_tags: ['damage', 'melee'], validation_status: 'valid', validation_errors: [],
  }],
  enemy_spells: [{
    id: 'goblin_strike', discipline_id: '', name: 'Estoc rouillé', description: 'Une attaque directe.', ap_cost: 2, minimum_range: 1, range: 1, needs_line_of_sight: true, cooldown_activations: 0, initial_cooldown: 0, max_uses_per_combat: 0, once_per_activation: false, can_target_enemy: true, can_target_ally: false, can_target_free_cell: false, can_target_self: false, aoe_shape: { value: 0, name: 'single' }, aoe_size: 1, line_from_caster: false, damage: 16, heal: 0, shield_grant: 0, damage_type: { value: 0, name: 'physical' }, element: { value: 0, name: 'none' }, critical_chance: 0, terrain_effect: null, applied_status: null, push_distance: 0, pull_distance: 0, collision_damage: 0, cluster_bonus_damage: 0, ap_drain: 0, teleport_behind_target: false, delayed_resolution: { value: 0, name: 'none' }, summon: null, summon_type: '', modifiers: [], serialization_warnings: [], icon_path: '', vfx_scene_path: '', sound_path: '', source_path: 'res://data/spells/enemies/goblin_strike.tres', referenced_by_enemy_ids: ['goblin'], summon_enemy_id: '', summon_starting_hp: 0, summon_max_living_team: 0, summon_initial_cooldowns: {}, condition_hp_at_or_below: -1, requires_absent_unit_id: '', encounter_enabled_in_ids: ['encounter.room.01'], encounter_disabled_in_ids: [], effect_tags: ['damage', 'melee'],
  }],
  ai_profiles: [{
    id: 'goblin_rush', source_path: 'res://data/ai/goblin_rush.tres', strategy: { name: 'MELEE_RUSH', value: 0, description: 'Assaut de mêlée' }, marked_status_id: '', normal_role_id: 'skirmisher', chief_role_id: '', commander_role_id: '', sentence_hp_ratio_threshold: 0, commander_emergency_hp: 0, summon_when_normals_below: 0, ideal_minimum_range: 1, ideal_maximum_range: 1, avoid_hero_adjacency: false, prefer_living_neighbors: false, protect_commander_paths: false, commander_distance_penalty_per_cell: 0, commander_path_block_bonus: 0, referenced_by_enemy_ids: ['goblin'],
  }],
  contract_checks: [
    { key: 'combat.base_ap', target: 6, observed_value: 6, status: 'conform', truth_status: 'verified', affected_entity_type: '', affected_entity_ids: [], evidence: 'UnitData.max_ap', message: 'Conforme.' },
    { key: 'progression.xp', target: 1, observed_value: null, status: 'not_evaluated', truth_status: 'non_certified', affected_entity_type: '', affected_entity_ids: [], evidence: 'Aucune preuve statique.', message: 'Non évalué.' },
  ],
  audit_results: [{ rule_id: 'CONTRACT.NOT_EVALUATED', severity: 'info', status: 'open', truth_status: 'verified', suggested_action_truth_status: 'recommendation', domain: 'contract', entity_type: 'contract_check', entity_id: 'progression.xp', affected_entity_type: 'contract_check', affected_entity_ids: ['progression.xp'], message: 'Cible non évaluée.', source_path: 'docs/observatory/design_contract.json', evidence: 'Aucune preuve.', suggested_action: 'Exporter une preuve.' }],
};
