const fs=require('fs'),path=require('path');
const folder='art/source/characters/achilles/passe_rive_iso_v1';
const actions={
 sky_bow:{source:'passe_rive_bow_v1/bow_rgb.png',rows:3,poses:'1 ready bow lowered, 2 raise bow to 35 degrees toward the sky and begin drawing, 3 FULL DRAW: left bow arm straight, right drawing elbow far back, hand anchored beside jaw, torso leaned backwards, both feet planted, 4 release arrow with right hand open beside cheek and bow still high, 5 follow through and lower bow, 6 ready bow lowered. Spear and shield strapped to the back throughout. Bow held in anatomical LEFT hand, string drawn with anatomical RIGHT hand. A single taut bowstring and a single arrow until release.'},
 ivory_bow:{source:'passe_rive_ivory_bow_v1/ivory_rgb.png',rows:3,poses:'1 ready normal bow, 2 descend onto bent REAR leg with other leg extended toward target and draw at 5 degrees above horizontal, 3 FULL POWER bow transforms into thick robust IVORY limbs, right drawing upper arm visibly more powerful but rest of body stays slender, right elbow far back, drawing hand at cheek, 4 sustained full charge same anchored stance and same muscular right drawing arm, 5 release: right fingers open, maintain bow-arm extension and planted feet, 6 recover upright holding normal bow lowered. Spear and shield strapped to the back throughout. Bow held in anatomical LEFT hand, string drawn with anatomical RIGHT hand. Torso recoils back while drawing, never reverses aim.'},
 vital_harvest:{source:'passe_rive_vital_harvest_v1/vital_rgb.png',rows:3,poses:'1 standing neutral UNARMED, hands beside body, 2 elbows slightly flex and palms turn out green, 3 levitate gently, toes point down, chest pushes FORWARD in facing direction and head arches BACK, open palms green with arms low beside hips, 4 stronger chest opening and head thrown backwards with green palms (red chest burst will be added later; DO NOT paint the burst), 5 sustain levitation with chest open, 6 gently return to neutral feet grounded. NO weapons anywhere: no spear, no shield, no bow on the back either. No painted auras, no glow background, only pale green palms. Keep costume, hood and adult body from reference.'},
 fauche:{source:'passe_rive_fauche_v1/fauche_rgb.png',rows:4,poses:'1 wide low stance knees bent, pelvis loads rear leg, spear head trailing far behind, anatomical RIGHT hand gripping the very BUTT of spear; 2 hip rotation leads spear passing BEHIND body toward target; 3 spear sweeps outward at waist height toward target; 4 maximal extension and fast lateral sweep driven by pelvis and right shoulder; 5 tip comes across FOREGROUND diagonally down with foreshortening; 6 broad follow-through to the opposite side, weight shifts to other leg; 7 decelerate and lift spear; 8 stable recovered combat guard. Shield strapped on BACK throughout. Anatomical LEFT hand remains open counterbalance, never takes weapon. Spear butt in right palm continuously, long shaft extends away from hand, single spearhead. Only torso rotation required by swing, camera remains fixed for every pose. No painted trail: separate effect added later.'},
 walk:{source:'passe_rive_walk_v3/candidate_b_rgb.png',rows:3,cols:4,poses:'12 successive poses of ONE complete walking cycle, TWO alternating steps. 1 right heel touches in FRONT, left toes behind; 2 right foot plants, body drops; 3 left foot lifts behind, right supports; 4 left foot passes UNDER pelvis with bent knee, right foot supports; 5 left leg swings forward with toe lifted, right heel lifts behind; 6 left heel reaches in front; 7 LEFT heel CONTACT in front and right toes behind, opposite of pose 1; 8 left plants, body drops; 9 right foot lifts behind; 10 right bent knee passes UNDER pelvis, left supports; 11 right leg swings forward with toe lifted, left heel lifts behind; 12 right heel reaches forward for seamless pose 1. These MUST be twelve DIFFERENT evolving leg poses: do NOT repeat a single rear bent leg in all cells. Feet trace the same ground line in the facing direction. Upper body stable, subtle alternating hip/shoulder rotation, controlled vertical head bob. Carry spear vertical in RIGHT hand, shield diagonal in LEFT forearm. Neither weapon changes hand or vanishes. This is an in-place loop: pelvis at same ground coordinate, stance foot slides opposite the travel vector while swing foot lifts then advances. Camera never rotates.'}
};
const angles={
 S:'FRONT three-quarter facing SCREEN LOWER LEFT, matching SECOND character of turnaround. Mask nose and toes point LEFT. Chest visible, anatomical left shield/bow arm on near side, right spear/drawing arm farther from camera. Action reference faces right and supplies timing ONLY: all poses must be redrawn facing LEFT.',
 N:'BACK three-quarter facing SCREEN UPPER RIGHT, matching THIRD character of turnaround. BACK hood and BACK cape visible; torso mostly rear, tiny mask edge only at right. No front brooch painted on back. Action goes diagonally away to RIGHT. Anatomical right arm nearer camera on screen right, left arm farther on screen left.',
 W:'BACK three-quarter facing SCREEN UPPER LEFT, matching FOURTH character of turnaround. BACK hood and BACK cape visible; torso mostly rear, tiny mask edge only at left. No front brooch painted on back. Action goes diagonally away to LEFT. Anatomical left arm nearer camera on screen left, right arm farther on screen right.'
};
const jobs=[];
for(const [id,a] of Object.entries(actions))for(const [dir,angle] of Object.entries(angles)){
 const cols=a.cols||2;
 const prompt=`Create a clean game sprite animation sheet for Passe-rive, exactly ${cols*a.rows} full body painted sprites arranged in ${cols} columns by ${a.rows} rows, READING ORDER left-to-right then top-to-bottom. Use input 1 for action phases and character design, input 2 for canonical camera orientation. Keep the adult slender angular ivory-mask underworld ferryman, petrol hood, muted jade draped fabric, black fitted limbs, ivory waist sash, bronze cuffs, sandals. Flat readable painted shapes, fine crisp edge, very restrained texture. Orthographic camera slightly elevated for a 2D isometric game, fixed framing and consistent anatomy in all cells. Preserve body size, weapon lengths, and face design. Full spear/bow and every toe inside cells with white gaps between all figures; each figure is separate on a perfectly plain WHITE background, no checkerboard, no shadow, no text, no labels, no extra drawings.\nCAMERA: ${angle}\nACTION ${id}, ordered phases: ${a.poses}\nDraw the correct near and far surfaces; do not merely reflect the source and exchange anatomical hands. The requested facing direction is consistent from first to last pose. Make every pose large, clean and readable; retain feet separation, correct bend directions, balanced weight and grounded contact.`;
 const file=`${id}_${dir}_prompt.txt`;fs.writeFileSync(path.join(folder,file),prompt);
 jobs.push({id,dir,cols,rows:a.rows,prompt_file:file,source:'art/source/characters/achilles/'+a.source});
}
fs.writeFileSync(path.join(folder,'extended_jobs.json'),JSON.stringify(jobs,null,2));
console.log(`${jobs.length} directional action prompts prepared`);
