const fs=require('fs'),path=require('path');
const dir='art/source/characters/achilles/passe_rive_iso_v1';
const definitions=JSON.parse(fs.readFileSync('tools/passe_rive_spells/layout.json')).actions;
const common=`Use case: stylized-concept. Production 2D isometric game sprite sheet, genuinely transparent background, or clean plain white if unavailable. NEVER draw a checkerboard. No labels, lettering, borders, platform, ground shadow, VFX, motion streak or duplicate ghost limbs. Input 1 is the current action key-pose reference, Input 2 is the character's four-angle costume turnaround. Match their SAME adult slender Passe-rive, ivory angular mask, petrol hood, muted jade drape, small bronze brooch, black limbs, ivory sash, bronze cuffs, sandals. Simple crisp painted game art and broad color shapes, no added muscle detail or ornaments. Fixed slightly elevated orthographic camera, same body proportions and scale in all frames. Repaint the anatomy and equipment occlusion for the requested viewpoints. The spear is always held by ANATOMICAL RIGHT hand, oval diagonal shield by ANATOMICAL LEFT hand; never swap equipment by mirroring. Back views show hood back and rear jade cape, not the front mask/brooch drawn on the back. Frame every character AND all weapons entirely inside its own cell, with generous empty gutters. The supplied action's four original poses in reading order must be reproduced as the same movement from new angles, not generic standing poses.\n`;
const descriptions={strike:'Spear thrust. Row 1: coil with elbow drawn back, spear near hip. Row 2: full extension of spear arm with weight on bent forward leg, sharp thrust toward the facing direction. Row 3: retract spear, low knees. Row 4: settled ready diagonal spear and shield. Feet stay in the same two planted spots; hips lead.',dash:'Forward dash. Row 1: low compression, forward knee bent, spear behind, shield in front. Row 2: airborne powerful horizontal leap toward the facing direction, both feet off ground, cloth trailing opposite. Row 3: absorb landing with bent forward leg. Row 4: ready spear/shield stance. No effects painted.',shot:'Overarm spear projection. Row 1: right arm raises spear over shoulder. Row 2: wind up shoulder farther back, opposite knee lifts. Row 3: explosive full overarm extension toward facing direction, rear heel pivots, spear still in right hand at release. Row 4: follow through low and across, recovered spear diagonal in hand. Left shield stays attached to left forearm.',guard:'Diagonal oval shield guard. Row 1: balanced stance, spear vertical, shield relaxed. Row 2: widen feet and raise shield before torso. Row 3: low braced knee bend behind the shield, firm contact stance. Row 4: shield pushes outward then holds cover. Spear remains in right hand. Shield is long diagonal/vertical, never horizontal like a tray.',sweep:'High-to-low spear sweep. Row 1: arm spear above and behind shoulder, wide planted feet. Row 2: arm sweeps spear fully across toward facing direction. Row 3: follow blade downward with pelvis and shoulders, rear heel pivots, knees flex. Row 4: return diagonal spear guard. Left hand always carries shield.',bash:'Shield bash. Row 1: gather behind shield, soft knees. Row 2: drive shoulder and shield forward, opposite spear arm extends backward for balance. Row 3: full shield impact extension toward facing direction, deep bent front knee and long rear leg. Row 4: rebound to ready guard. Keep left hand on shield and right on spear.'};
for(const a of definitions.slice(0,6)){
 const prompt=common+`\nLayout exactly THREE COLUMNS by FOUR ROWS = TWELVE complete full-body sprites, portrait sheet, preferably 1536x2048. Each COLUMN is one consistent direction, each ROW is one action phase.\nLEFT COLUMN (S): three-quarter FRONT facing screen LOWER LEFT, toward viewer. See figure 2 of turnaround. Mask and chest visible; left-arm shield is camera-near, right-arm spear farther. Every attack points LEFT.\nMIDDLE COLUMN (N): three-quarter BACK facing screen UPPER RIGHT, AWAY from viewer. See figure 3. Hood back and cape visible, only a sliver of mask at right edge. Attacks point RIGHT and away.\nRIGHT COLUMN (W): three-quarter BACK facing screen UPPER LEFT, AWAY from viewer. See figure 4. Hood back and cape visible, sliver of mask at left edge. Attacks point LEFT and away.\nDo not put any front-right/E view in this sheet; it already exists. These must be THREE clearly different sides, never mirrored duplicates. Camera does not rotate within a column.\nAction ${a.name}: ${descriptions[a.id]}\nKeep body heights consistent; body fits within 70 percent of each cell height, including the upright stance. Provide clean white outer margins including top row spear tips, no objects touching image borders. The whole figure and complete weapon must fit each cell.`;
 fs.writeFileSync(path.join(dir,`${a.id}_directions_prompt.txt`),prompt);
}
console.log('SIX_DIRECTION_PROMPTS_READY');
