param([string]$ProjectRoot=(Split-Path -Parent $PSScriptRoot))
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
$source=Get-Content -Raw -LiteralPath (Join-Path $ProjectRoot 'data\maps\mountain_pass_blockout.tres')
$out=Join-Path $ProjectRoot 'artifacts\maps\mountain_pass_blockout';$null=New-Item -ItemType Directory -Force $out
function MatchValue($pattern){$m=[regex]::Match($source,$pattern);if(-not$m.Success){throw"Missing $pattern"};$m.Groups[1].Value}
$layout=MatchValue 'layout_rows\s*=\s*PackedStringArray\(([^\r\n]+)\)';$rows=@([regex]::Matches($layout,'"([^"]+)"')|%{$_.Groups[1].Value})
function Vec($name){$m=[regex]::Match($source,"$name\s*=\s*Vector2\(([-\d.]+),\s*([-\d.]+)\)");@([single]$m.Groups[1].Value,[single]$m.Groups[2].Value)}
$origin=Vec 'grid_origin';$ax=Vec 'axis_x';$ay=Vec 'axis_y';$cliff=[single](MatchValue 'cliff_depth\s*=\s*([\d.]+)');$obstacle=[single](MatchValue 'obstacle_height\s*=\s*([\d.]+)');$landmark=[single](MatchValue 'landmark_height\s*=\s*([\d.]+)')
$road=[Collections.Generic.HashSet[string]]::new();$roadText=MatchValue 'road_visual_cells\s*=\s*Array\[Vector2i\]\(([^\r\n]+)\)';foreach($m in [regex]::Matches($roadText,'Vector2i\((\d+),\s*(\d+)\)')){$null=$road.Add("$($m.Groups[1].Value),$($m.Groups[2].Value)")}
function C($hex,[int]$a=255){$h=$hex.TrimStart('#');[Drawing.Color]::FromArgb($a,[Convert]::ToInt32($h.Substring(0,2),16),[Convert]::ToInt32($h.Substring(2,2),16),[Convert]::ToInt32($h.Substring(4,2),16))}
function P([single]$x,[single]$y){[Drawing.PointF]::new($x,$y)}
function Sym([int]$x,[int]$y){if($x-lt0-or$x-ge14-or$y-lt0-or$y-ge14){'X'}else{$rows[$y].Substring($x,1)}}
function Center([int]$x,[int]$y){P ($origin[0]+$x*$ax[0]+$y*$ay[0]) ($origin[1]+$x*$ax[1]+$y*$ay[1])}
function Diamond([int]$x,[int]$y){$c=Center $x $y;$hw=[Math]::Abs($ax[0]-$ay[0])*.5;$hh=[Math]::Abs($ax[1]+$ay[1])*.5;[Drawing.PointF[]]@((P $c.X ($c.Y-$hh)),(P ($c.X+$hw) $c.Y),(P $c.X ($c.Y+$hh)),(P ($c.X-$hw) $c.Y))}
function FillPoly($g,[Drawing.PointF[]]$p,[Drawing.Color]$color){$b=[Drawing.SolidBrush]::new($color);try{$g.FillPolygon($b,$p)}finally{$b.Dispose()}}
function Stroke($g,[Drawing.PointF[]]$p,[Drawing.Color]$color,[single]$w=1){$pen=[Drawing.Pen]::new($color,$w);$pen.LineJoin=[Drawing.Drawing2D.LineJoin]::Round;try{$g.DrawPolygon($pen,$p)}finally{$pen.Dispose()}}
function FillRect($g,$x,$y,$w,$h,[Drawing.Color]$color){$b=[Drawing.SolidBrush]::new($color);try{$g.FillRectangle($b,$x,$y,$w,$h)}finally{$b.Dispose()}}
function Cells{$r=[Collections.Generic.List[object]]::new();for($y=0;$y-lt14;$y++){for($x=0;$x-lt14;$x++){if((Sym $x $y)-ne'X'){$r.Add([pscustomobject]@{X=$x;Y=$y;C=(Center $x $y)})}}};@($r|Sort-Object{$_.C.Y},{$_.C.X})}
function Edges{$dirs=@(@{N='U';X=0;Y=-1;A=0;B=1},@{N='R';X=1;Y=0;A=1;B=2},@{N='D';X=0;Y=1;A=2;B=3},@{N='L';X=-1;Y=0;A=3;B=0});$r=[Collections.Generic.List[object]]::new();foreach($cell in (Cells)){$d=Diamond $cell.X $cell.Y;foreach($dir in $dirs){if((Sym ($cell.X+$dir.X) ($cell.Y+$dir.Y))-eq'X'){$a=$d[$dir.A];$b=$d[$dir.B];$r.Add([pscustomobject]@{N=$dir.N;A=$a;B=$b;Z=($a.Y+$b.Y)/2})}}};@($r|Sort-Object Z)}
function Groups($target){$left=[Collections.Generic.HashSet[string]]::new();for($y=0;$y-lt14;$y++){for($x=0;$x-lt14;$x++){if((Sym $x $y)-eq$target){$null=$left.Add("$x,$y")}}};$all=[Collections.Generic.List[object]]::new();while($left.Count-gt0){$q=[Collections.Generic.Queue[string]]::new();$group=[Collections.Generic.List[object]]::new();$seed=@($left)[0];$q.Enqueue($seed);$null=$left.Remove($seed);while($q.Count-gt0){$v=$q.Dequeue().Split(',');$x=[int]$v[0];$y=[int]$v[1];$group.Add([pscustomobject]@{X=$x;Y=$y});foreach($dir in @(@(0,-1),@(1,0),@(0,1),@(-1,0))){$k="$($x+$dir[0]),$($y+$dir[1])";if($left.Remove($k)){$q.Enqueue($k)}}};$all.Add(@($group))};@($all)}
function Hull([Drawing.PointF[]]$inputPoints){$u=@{};foreach($p in $inputPoints){$u["$($p.X),$($p.Y)"]=$p};$pts=@($u.Values|Sort-Object X,Y);function Cross($o,$a,$b){(($a.X-$o.X)*($b.Y-$o.Y))-(($a.Y-$o.Y)*($b.X-$o.X))};$lo=[Collections.Generic.List[Drawing.PointF]]::new();foreach($p in $pts){while($lo.Count-ge2-and(Cross $lo[$lo.Count-2] $lo[$lo.Count-1] $p)-le0){$lo.RemoveAt($lo.Count-1)};$lo.Add($p)};$up=[Collections.Generic.List[Drawing.PointF]]::new();for($i=$pts.Count-1;$i-ge0;$i--){$p=$pts[$i];while($up.Count-ge2-and(Cross $up[$up.Count-2] $up[$up.Count-1] $p)-le0){$up.RemoveAt($up.Count-1)};$up.Add($p)};$lo.RemoveAt($lo.Count-1);$up.RemoveAt($up.Count-1);[Drawing.PointF[]]@($lo.ToArray()+$up.ToArray())}
function Back($g,[bool]$height){$r=if($height){C '525252'}else{C '7f8991'};$s=if($height){C '6b6b6b'}else{C 'e2e7e9'};FillPoly $g ([Drawing.PointF[]]@((P 80 560),(P 250 405),(P 420 490),(P 600 295),(P 790 480),(P 940 370),(P 1120 500),(P 1320 315),(P 1510 470),(P 1690 380),(P 1968 570),(P 1968 625),(P 80 625))) $r;FillPoly $g ([Drawing.PointF[]]@((P 105 558),(P 250 430),(P 420 510),(P 600 330),(P 790 510),(P 940 405),(P 1120 525),(P 1320 350),(P 1510 500),(P 1690 415),(P 1940 580),(P 1940 622),(P 105 622))) $s;FillPoly $g ([Drawing.PointF[]]@((P 90 720),(P 260 650),(P 430 720),(P 390 1010),(P 180 1110),(P 70 980))) $r;FillPoly $g ([Drawing.PointF[]]@((P 1958 720),(P 1780 650),(P 1615 735),(P 1655 1030),(P 1870 1110),(P 1980 975))) $r}
function Front($g,[bool]$height){$r=if($height){C '424242'}else{C '68737c'};$s=if($height){C '616161'}else{C 'e7ebed'};FillPoly $g ([Drawing.PointF[]]@((P 80 1290),(P 255 1200),(P 390 1305),(P 320 1435),(P 100 1455))) $r;FillPoly $g ([Drawing.PointF[]]@((P 1968 1280),(P 1780 1195),(P 1650 1315),(P 1735 1440),(P 1950 1455))) $r;FillPoly $g ([Drawing.PointF[]]@((P 92 1292),(P 255 1220),(P 370 1308),(P 300 1360),(P 120 1368))) $s;FillPoly $g ([Drawing.PointF[]]@((P 1955 1285),(P 1785 1218),(P 1670 1318),(P 1750 1365),(P 1930 1370))) $s}
function DrawCliffs($g,[bool]$height){foreach($e in (Edges)){$color=if($height){C '2e2e2e'}elseif($e.N-in @('R','D')){C '4b555e'}else{C '59646e'};$face=[Drawing.PointF[]]@($e.A,$e.B,(P $e.B.X ($e.B.Y+$cliff)),(P $e.A.X ($e.A.Y+$cliff)));FillPoly $g $face $color;if(-not$height){Stroke $g $face (C '273039' 170) 1}}}
function Ground($g,$mode){foreach($cell in (Cells)){$sym=Sym $cell.X $cell.Y;$key="$($cell.X),$($cell.Y)";$color=if($sym-eq'~'){C 'badde8'}elseif($road.Contains($key)){C 'c9c4bc'}else{C 'edf1f3'};$d=Diamond $cell.X $cell.Y;FillPoly $g $d $color;if($sym-eq'A'){FillPoly $g $d (C '338ee8' 62)};if($sym-eq'E'){FillPoly $g $d (C 'dc5149' 62)};if($mode-ne'clean'){Stroke $g $d (C '304656' 120) 1}}}
function Obstacles($g,[bool]$height){$list=[Collections.Generic.List[object]]::new();foreach($group in @((Groups '#')+(Groups 'R'))){$z=-1;foreach($cell in $group){$z=[Math]::Max($z,(Center $cell.X $cell.Y).Y)};$list.Add([pscustomobject]@{G=$group;Z=$z})};foreach($entry in @($list|Sort-Object Z)){$group=$entry.G;$points=[Collections.Generic.List[Drawing.PointF]]::new();foreach($cell in $group){$points.AddRange([Drawing.PointF[]](Diamond $cell.X $cell.Y))};$base=Hull ([Drawing.PointF[]]$points.ToArray());$isR=(Sym $group[0].X $group[0].Y)-eq'R';$h=if($isR){$landmark}else{$obstacle};$cx=($base|Measure-Object X -Average).Average;$cy=($base|Measure-Object Y -Average).Average;$top=[Drawing.PointF[]]@($base|%{P ($cx+($_.X-$cx)*.78) ($cy+($_.Y-$cy)*.78-$h)});$side=if($height){C '404040'}elseif($isR){C '394148'}else{C '444d55'};for($i=0;$i-lt$base.Count;$i++){$j=($i+1)%$base.Count;FillPoly $g ([Drawing.PointF[]]@($base[$i],$base[$j],$top[$j],$top[$i])) $side};$shade=if($height){C '858585'}elseif($isR){C '59636c'}else{C '65717a'};FillPoly $g $top $shade;if(-not$height){Stroke $g $base (C '283139' 220) 1.5;Stroke $g $top (C 'e2ebef' 105) 1}}}
function Mask($g){$p=@{'.'=C 'd9e0e4';'~'=C '78cde5';'#'=C '48525b';'R'=C '6d526f';'X'=C '222a31';'A'=C '338ee8';'E'=C 'dc5149'};for($y=0;$y-lt14;$y++){for($x=0;$x-lt14;$x++){$d=Diamond $x $y;FillPoly $g $d $p[(Sym $x $y)];Stroke $g $d (C '101820' 150) 1}}}
function DebugDraw($g){$p=@{'.'=C 'd9e0e4' 74;'~'=C '78cde5' 82;'#'=C '48525b' 105;'R'=C '6d526f' 115;'X'=C '222a31' 175;'A'=C '338ee8' 100;'E'=C 'dc5149' 100};$font=[Drawing.Font]::new([Drawing.FontFamily]::GenericMonospace,9,[Drawing.FontStyle]::Bold,[Drawing.GraphicsUnit]::Pixel);$brush=[Drawing.SolidBrush]::new((C '17212a'));try{for($y=0;$y-lt14;$y++){for($x=0;$x-lt14;$x++){$sym=Sym $x $y;$d=Diamond $x $y;FillPoly $g $d $p[$sym];Stroke $g $d (C '17212a' 145) 1;$c=Center $x $y;$g.FillEllipse($brush,$c.X-2.5,$c.Y-2.5,5,5);$g.DrawString("$x,$y $sym",$font,$brush,$c.X-22,$c.Y-16)}};$g.FillEllipse([Drawing.SolidBrush]::new((C 'ffcf4a')),$origin[0]-7,$origin[1]-7,14,14);$g.DrawString('ORIGIN',$font,$brush,$origin[0]+10,$origin[1]-10)}finally{$font.Dispose();$brush.Dispose()}}
function Render($mode){$bmp=[Drawing.Bitmap]::new(2048,2048,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$g=[Drawing.Graphics]::FromImage($bmp);$g.SmoothingMode=[Drawing.Drawing2D.SmoothingMode]::AntiAlias;FillRect $g 0 0 2048 2048 (C 'd8dde2');if($mode-eq'mask'){Mask $g}elseif($mode-eq'height'){FillRect $g 0 0 2048 2048 (C 'ebebeb');Back $g $true;DrawCliffs $g $true;foreach($cell in (Cells)){FillPoly $g (Diamond $cell.X $cell.Y) (C 'b8b8b8')};Obstacles $g $true;Front $g $true}else{Back $g $false;DrawCliffs $g $false;Ground $g $mode;Obstacles $g $false;Front $g $false;if($mode-eq'debug'){DebugDraw $g}};$g.Dispose();$bmp}
$exports=[ordered]@{'mountain_pass_blockout_reference.png'='reference';'mountain_pass_blockout_clean.png'='clean';'mountain_pass_blockout_debug.png'='debug';'mountain_pass_blockout_logic_mask.png'='mask';'mountain_pass_blockout_height_guide.png'='height'};foreach($e in $exports.GetEnumerator()){$bmp=Render $e.Value;$path=Join-Path $out $e.Key;try{$bmp.Save($path,[Drawing.Imaging.ImageFormat]::Png)}finally{$bmp.Dispose()};"EXPORTED $($e.Key) 2048x2048"}
$cmp=[Drawing.Bitmap]::new(2048,2048);$g=[Drawing.Graphics]::FromImage($cmp);FillRect $g 0 0 2048 2048 (C 'c7cdd2');$names=@('mountain_pass_blockout_reference.png','mountain_pass_blockout_clean.png','mountain_pass_blockout_debug.png');$xs=@(32,704,1376);for($i=0;$i-lt3;$i++){FillRect $g ($xs[$i]-5) 699 650 650 (C '47535d');$img=[Drawing.Image]::FromFile((Join-Path $out $names[$i]));try{$g.DrawImage($img,[Drawing.RectangleF]::new($xs[$i],704,640,640))}finally{$img.Dispose()}};$g.Dispose();try{$cmp.Save((Join-Path $out 'mountain_pass_blockout_comparison.png'),[Drawing.Imaging.ImageFormat]::Png)}finally{$cmp.Dispose()};'EXPORTED mountain_pass_blockout_comparison.png 2048x2048'
