"""Read-only PNG analysis, atlas registration and explicit Godot dependencies.

Never edits raster pixels. Source files are copied byte for byte into the game.
"""
from pathlib import Path
import json
import hashlib
import argparse
import numpy as np
from PIL import Image

GAME = Path(__file__).resolve().parents[2]
PACK = GAME / 'assets/characters/PasseRive/sprites_s20'


def cut(values, expected, radius):
    lo, hi = max(0, int(expected-radius)), min(len(values), int(expected+radius))
    band = values[lo:hi]
    ids = np.flatnonzero(band == band.min())
    groups = np.split(ids, np.where(np.diff(ids) > 1)[0]+1)
    best = max(groups, key=len)
    return lo+int((best[0]+best[-1])/2)


def analyze(path):
    im = Image.open(path)
    assert im.mode == 'RGBA', f'{path}: no alpha'
    rgba = np.asarray(im)
    alpha = rgba[:, :, 3]
    mask = alpha > 64
    h, w = alpha.shape
    assert (alpha == 0).mean() > .2, f'{path}: no transparent background'
    rows = [0] + [cut(mask.sum(1), h*i/3, h/3*.14) for i in (1, 2)] + [h]
    frames = []
    for row in range(3):
        ya, yb = rows[row:row+2]
        cols = [0] + [cut(mask[ya:yb].sum(0), w*i/4, w/4*.12) for i in (1, 2, 3)] + [w]
        for col in range(4):
            xa, xb = cols[col:col+2]
            sub = mask[ya:yb, xa:xb]
            yy = np.flatnonzero(sub.sum(1) > 4)
            xx = np.flatnonzero(sub.sum(0) > 4)
            assert len(xx) and len(yy), f'{path}: empty cell {row},{col}'
            left, right = max(xa, xa+xx[0]-3), min(xb, xa+xx[-1]+4)
            top, bottom = max(ya, ya+yy[0]-3), min(yb, ya+yy[-1]+4)
            ground = ya+int(yy[-1])
            anchor = (col+.5)*w/4
            frames.append({'rect':[int(left),int(top),int(right-left),int(bottom-top)],
                           'pivot':[round(anchor-left,2),int(ground-top)],
                           'cell':[xa,ya,xb-xa,yb-ya], 'ground_y':ground})
    # Register anatomical height from the petrol hood, not the raised weapon.
    x,y,cw,ch = frames[0]['cell']
    first = rgba[y:y+ch,x:x+cw].astype(float)
    r,g,b,a = [first[:,:,i] for i in range(4)]
    hood = (r < 65) & (g > r*1.25) & (g < 110) & (b > g*.85) & (a > 128)
    hood_y = np.flatnonzero(hood.sum(1) > 8)
    assert len(hood_y), f'{path}: cannot locate hood'
    body_height = frames[0]['ground_y'] - (y+int(hood_y[0]))
    return {'file':'atlases/'+path.name, 'width':w, 'height':h,
            'frames':frames, 'scale':round(330/body_height,6),
            'body_height':body_height, 'sha256':hashlib.sha256(path.read_bytes()).hexdigest()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify metadata and PNG hashes without writing.')
    args = parser.parse_args()
    result = {}
    for path in sorted((PACK/'atlases').glob('*.png')):
        ident = path.stem.replace('PR_SEAL_v03_', 'PR_SEAL_')
        result[ident] = analyze(path)
    assert len(result) == 36, 'Expected four angles for nine clips'
    # The wide thrust's two dagger tips cross cell boundaries. Register the
    # source pieces on their own pose and exclude them from adjacent poses.
    riposte = result['PR_RIPOSTE_SE']['frames']
    tip_regions = [(5, [707, 493, 19, 42]), (7, [1092, 586, 40, 40])]
    hero_frame = riposte[6]
    anchor_x = hero_frame['rect'][0] + hero_frame['pivot'][0]
    for neighbor, rect in tip_regions:
        riposte[neighbor].setdefault('exclude', []).append(rect)
        hero_frame.setdefault('effects', []).append({
            'rect': rect,
            'pivot': [anchor_x - rect[0], hero_frame['ground_y'] - rect[1]],
        })
    # S22 visual audit: the seal above poses 4/5 crosses into cells 0/1.
    # Keep it with the raised hand, never under the preceding pose's boots.
    seal = result['PR_SEAL_SE']
    for neighbor, owner, rect, ground in [
        (0, 4, [72, 374, 76, 33], 377),
        (1, 5, [433, 374, 82, 33], 378),
    ]:
        prior = seal['frames'][neighbor]
        prior.setdefault('exclude', []).append(rect)
        prior['ground_y'] = ground
        prior['pivot'][1] = ground - prior['rect'][1]
        current = seal['frames'][owner]
        anchor_x = current['rect'][0] + current['pivot'][0]
        current.setdefault('effects', []).append({
            'rect': rect,
            'pivot': [anchor_x - rect[0], current['ground_y'] - rect[1]],
        })
    seal['body_height'] -= 406 - 377
    seal['scale'] = round(330 / seal['body_height'], 6)
    text = '# Generated by tools/class_card_vfx/build_s20_data.py. Pixels unchanged.\nextends RefCounted\n'
    text += '\nconst REGIONS := '+json.dumps(result,indent='\t')+'\n'
    text += '\nconst TEXTURES := {\n'
    for ident, info in result.items():
        text += f'\t"{ident}": preload("res://assets/characters/PasseRive/sprites_s20/{info["file"]}"),\n'
    text += '}\n'
    targets = {
        PACK/'atlas_regions.json': json.dumps(result, indent=2),
        GAME/'characters/achilles/2d/passe_rive_s20_data.gd': text,
    }
    for path, content in targets.items():
        if args.check:
            assert path.read_text(encoding='utf-8') == content, f'Stale generated data: {path}'
        elif not path.exists() or path.read_text(encoding='utf-8') != content:
            path.write_text(content, encoding='utf-8')
    print(json.dumps({'atlases': len(result), 'poses': sum(len(x['frames']) for x in result.values()), 'mode': 'check' if args.check else 'build'}))


if __name__ == '__main__':
    main()
