"""Measure clothed silhouette coverage to bound the apparent mass of attacks.

This is a visual calibration aid, not a skeletal/anatomical measurement. Uses a
single correction for all poses of a clip, preserving crouches and jumps.
"""
from pathlib import Path
import argparse,json
import numpy as np
from PIL import Image

GAME=Path(__file__).resolve().parents[2]
STANCE={'PR_BLADES':.90,'PR_RIPOSTE':.90,'PR_DAGGER':.94,'PR_SHOT':1.,'PR_VOLLEY':.96,'PR_EMBER':1.,'PR_SEAL':1.}


def area(im):
    a=np.asarray(im.convert('RGBA')).astype(float);r,g,b,alpha=a.transpose(2,0,1)
    hi=a[:,:,:3].max(2);lo=a[:,:,:3].min(2)
    garment=((b>r*1.15)&(g>r*1.2))|((g>r*1.025)&(g>=b*.99))|(hi-lo<hi*.18)
    return int(((alpha>220)&(hi<215)&garment).sum())


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args()
    native=GAME/'assets/characters/PasseRive/autosprite_v1'
    manifest=json.loads((native/'manifest.json').read_text())
    targets={}
    for row in manifest['sheets']:
        if row['stem']!='idle':continue
        key='idle_'+row['direction']
        targets[row['direction']]=area(Image.open(native/row['file']))/25*manifest['geometry'][key]['scale']**2
    entries={};factors={}
    for n in [19,20]:
        root=GAME/f'assets/characters/PasseRive/sprites_s{n}'
        for key,atlas in json.loads((root/'atlas_regions.json').read_text()).items():
            clip='_'.join(key.split('_')[:2]);direction=key.split('_')[-1] if n==20 else 'E'
            if clip not in STANCE:continue
            im=Image.open(root/atlas['file']);areas=[]
            for frame in atlas['frames']:
                x,y,w,h=frame['rect'];sample=im.crop((x,y,x+w,y+h))
                # Coverage measures exclude the known detached effect fragments.
                rgba=np.array(sample.convert('RGBA'))
                for cx,cy,cw,ch in frame.get('exclude',[]):
                    rgba[max(0,cy-y):min(h,cy+ch-y),max(0,cx-x):min(w,cx+cw-x),3]=0
                areas.append(area(Image.fromarray(rgba)))
            before=float(np.median(areas))*(atlas['scale']*214/330*STANCE[clip])**2
            # E art twists its chest into three-quarter view. Do not force the
            # area of a rigid side-on idle onto this deliberately open pose.
            reference=targets['SE' if direction=='E' else direction]
            # Open hands/legs uncover cloth hidden by the idle: permit +30%.
            estimate=float(min(1.,np.sqrt(reference*1.30/before)))
            # Coverage alone cannot distinguish an open stance from anatomy.
            # Visual review rejected 20–25% reductions: they shrink the head.
            # Bound this aid to 10%; larger differences need authored art work.
            correction=round(max(.90,estimate),6)
            factors[key]=correction
            entries[key]={'reference_area':reference,'before':before,'after':before*correction**2,'factor':correction,'coverage_candidate':estimate,'bounded_after_visual_review':estimate<.90,'first_pose_height':atlas.get('body_height',330/atlas['scale'])}
    outputs={
        GAME/'characters/achilles/2d/passe_rive_registration_data.gd':'# Generated by build_passe_rive_registration.py.\nextends RefCounted\nconst FACTORS := '+json.dumps(factors,indent='\t')+'\n',
        GAME/'art/source/passe_rive_s23/registration_audit.json':json.dumps({'method':'Median clothed coverage, allowance for open limbs; constant per atlas; visual review required.','entries':entries},indent=2),
    }
    for path,content in outputs.items():
        if args.check:assert path.read_text(encoding='utf-8')==content,str(path)
        else:path.write_text(content,encoding='utf-8')
    print(json.dumps({'atlases':len(entries),'mode':'check' if args.check else 'build','min_factor':min(factors.values())}))

if __name__=='__main__':main()
