"""Register generated drawings against Blender pose guides; never alter PNG pixels."""
from pathlib import Path
import json, hashlib, statistics, sys
import numpy as np
from PIL import Image

PROJECT = Path(__file__).resolve().parents[2]
SOURCE = PROJECT / 'art/source/passe_rive_s21'
CHECK = '--check' in sys.argv
DEST = PROJECT / 'assets/characters/PasseRive/sprites_s21'
DEST.mkdir(parents=True, exist_ok=True)

def bounds(mask, col, row):
    h,w = mask.shape
    x0,x1 = round(col*w/4),round((col+1)*w/4)
    y0,y1 = round(row*h/3),round((row+1)*h/3)
    yy,xx = np.where(mask[y0:y1,x0:x1])
    assert len(xx)>100
    return np.array([x0+xx.min(),y0+yy.min(),x0+xx.max()+1,y0+yy.max()+1],float)

regions = {}
for direction in ['E','SE','S','NE','N']:
    png=DEST/f'PR_LOCOMOTION_{direction}.png'
    image=np.asarray(Image.open(png).convert('RGBA'))
    guide=np.asarray(Image.open(SOURCE/f'walk_guide_{direction}.png').convert('RGB'))
    guide_mask=guide.min(axis=2)<160
    mask=image[:,:,3]>127
    assert (image[:,:,3]==0).sum() > image.shape[0]*image.shape[1]*.5
    gb=[bounds(guide_mask,i%4,i//4) for i in range(12)]
    ib=[bounds(mask,i%4,i//4) for i in range(12)]
    # One scale for the entire atlas. Registration preserves the guide's root,
    # including projected foot travel, rather than pinning its lowest pixel.
    ratio=statistics.median((b[3]-b[1])/(g[3]-g[1]) for b,g in zip(ib,gb))
    guide_height=gb[0][3]-gb[0][1]
    scale=330.0/(guide_height*ratio)
    frames=[]
    for i,(b,g) in enumerate(zip(ib,gb)):
        guide_root=np.array([(i%4+.5)*384, (i//4+.5)*512+150.4])
        root=(b[:2]+b[2:])/2 + (guide_root-(g[:2]+g[2:])/2)*ratio
        lo=np.maximum(b[:2]-2,0).astype(int)
        hi=np.minimum(b[2:]+2,[image.shape[1],image.shape[0]]).astype(int)
        frames.append({'rect':[int(lo[0]),int(lo[1]),int(hi[0]-lo[0]),int(hi[1]-lo[1])],
                       'pivot':np.round(root-lo,4).tolist(),
                       'guide_root':guide_root.tolist()})
    regions[direction]={'scale':round(scale,8),'guide_ratio':ratio,'body_height':guide_height*ratio,
                        'frames':frames,'source_sha256':hashlib.sha256(png.read_bytes()).hexdigest()}

def emit(path, text):
    if CHECK:
        assert path.read_text(encoding='utf-8') == text, str(path) + ' differs'
    else:
        path.write_text(text,encoding='utf-8')
emit(DEST/'atlas_regions.json', json.dumps(regions,indent=2))
code='## Generated by tools/class_card_vfx/build_s21_data.py. PNG pixels are unchanged.\n'
code+='extends RefCounted\nconst REGIONS = '+json.dumps(regions,ensure_ascii=False)+'\nconst TEXTURES = {\n'
for direction in regions:
    code+=f'"{direction}": preload("res://assets/characters/PasseRive/sprites_s21/PR_LOCOMOTION_{direction}.png"),\n'
code+='}\n'
emit(PROJECT/'characters/achilles/2d/passe_rive_s21_data.gd', code)
print(json.dumps({d:{'scale':r['scale'],'height':r['body_height']} for d,r in regions.items()},indent=2))
