"""Embed preserved metadata and explicit texture dependencies for Godot exports."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
pack = root / "assets/characters/PasseRive/sprites_s19"

def read(name):
    return json.loads((pack / name).read_text(encoding="utf-8"))

data = {
    "REGIONS": read("atlas_regions.json"),
    "CLIPS": {c["id"]: c for c in read("clips.json")},
    "CARDS": {c["id"]: c for c in read("cards.json")},
    "VFX": read("vfx_regions.json"),
}
text = "# Generated by tools/class_card_vfx/build_s19_data.py. Original pixels unchanged.\nextends RefCounted\n"
for key, value in data.items():
    text += "\nconst " + key + " := " + json.dumps(value, ensure_ascii=False, indent="\t") + "\n"
for constant, key in [("BODY_TEXTURES", "REGIONS"), ("VFX_TEXTURES", "VFX")]:
    text += "\nconst " + constant + " := {\n"
    for ident, info in data[key].items():
        text += f'\t"{ident}": preload("res://assets/characters/PasseRive/sprites_s19/{info["file"]}"),\n'
    text += "}\n"
(root / "characters/achilles/2d/passe_rive_s19_data.gd").write_text(text, encoding="utf-8")
