"""Measure RGBA source colors; emit shader calibration, without changing images."""
from pathlib import Path
import argparse, hashlib, json
import numpy as np
from PIL import Image

GAME = Path(__file__).resolve().parents[2]
GROUPS = ['teal','cape','leather','gold','ivory']


def colors(path):
    rgba = np.asarray(Image.open(path).convert('RGBA')).reshape(-1,4)
    rgb = rgba[rgba[:,3] > 240,:3].astype(float) / 255
    r,g,b = rgb.T
    hi,lo = rgb.max(1),rgb.min(1)
    sat = (hi-lo)/np.maximum(hi,.001)
    candidates = {
        'teal': (b>r*1.15)&(g>r*1.20)&(b>=g*.87)&(hi<.60),
        'cape': (g>.22)&(g>r*1.025)&(g>=b*.99)&(sat<.45),
        'gold': (r>.22)&(r<.78)&(r>g*1.12)&(g>b*1.30),
        'ivory': (r>.50)&(g>.46)&(b>.30)&(r>=g)&(sat<.50),
        'leather': (sat<.18)&(hi<.36)&(hi>.08),
    }
    used = np.zeros(len(rgb),bool); result={}
    for name,mask in candidates.items():
        valid = mask & ~used; used |= mask
        if valid.sum() >= 32:
            result[name]=np.median(rgb[valid],axis=0)
    return result


def main():
    parser=argparse.ArgumentParser(description=__doc__); parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    native=GAME/'assets/characters/PasseRive/autosprite_v1'
    target=colors(native/'PasseRive-iso_idle_southeast-v1.png')
    sources={}; measurements={}; hashes={}
    for folder in ['autosprite_v1','combat_v2']:
        root=GAME/'assets/characters/PasseRive'/folder
        manifest=json.loads((root/'manifest.json').read_text(encoding='utf-8'))
        for row in manifest.get('sheets',[]):
            path=root/row['file']
            stems=[row['stem']] if 'stem' in row else list(manifest['clips'])
            for stem in stems:
                key=stem+'_'+row['direction']
                if path.exists(): sources[key]=path
    for n in [19,20]:
        root=GAME/f'assets/characters/PasseRive/sprites_s{n}'
        for key,row in json.loads((root/'atlas_regions.json').read_text()).items():
            sources[key]=root/row['file']
    gains={}; centers={}
    for key,path in sorted(sources.items()):
        values=colors(path);gains[key]={};centers[key]={};measurements[key]={}
        for group in GROUPS:
            if group not in values: continue
            ratio=np.clip(target[group]/values[group],.65,1.50)
            gains[key][group]=[round(float(x),6) for x in ratio]
            centers[key][group]=[round(float(x),6) for x in values[group]]
            measurements[key][group]={
                'source_rgb':[round(float(x)*255,2) for x in values[group]],
                'target_rgb':[round(float(x)*255,2) for x in target[group]],
                'result_rgb':[round(float(x)*255,2) for x in values[group]*ratio],
            }
        hashes[key]=hashlib.sha256(path.read_bytes()).hexdigest()
    text='# Generated by build_passe_rive_palette.py; source pixels are unchanged.\nextends RefCounted\nconst SOURCES := '+json.dumps(gains,indent='\t')+'\n'
    text+='const CENTERS := '+json.dumps(centers,indent='\t')+'\n'
    outputs={GAME/'characters/achilles/2d/passe_rive_palette_data.gd':text,
             GAME/'art/source/passe_rive_s23/palette_audit.json':json.dumps({'reference':'autosprite_v1/idle_SE','measurements':measurements,'source_sha256':hashes},indent=2)}
    for path,content in outputs.items():
        if args.check: assert path.read_text(encoding='utf-8')==content, str(path)
        else: path.write_text(content,encoding='utf-8')
    print(json.dumps({'sources':len(gains),'groups':GROUPS,'mode':'check' if args.check else 'build'}))

if __name__=='__main__': main()
